name: export-and-branch-solution
on:
  workflow_dispatch:
jobs:
  build:

    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: 'https://make.powerapps.com/environments/Default-f926521e-0cde-404b-84af-812d6aa0c101/solutions?utm_source=office&utm_medium=app_launcher&utm_campaign=office_referrals'
        user-name: 'davidhamilton@anctraining.onmicrosoft.com'
        password-secret: ${{ secrets.Test }}
        solution-name: CDPDemo
        solution-output-file: 'CDPDemo.zip'
        working-directory: 'out'

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: 'out/CDPDemo.zip'
        solution-folder: 'out/solutions/CDPDemo'
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: 'https://make.powerapps.com/environments/Default-f926521e-0cde-404b-84af-812d6aa0c101/solutions?utm_source=office&utm_medium=app_launcher&utm_campaign=office_referrals'
        user-name: 'davidhamilton@anctraining.onmicrosoft.com'
        password-secret: ${{ secrets.Test }}

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: 'out/solutions/CDPDemo'
        solution-target-folder: 'src/solutions/CDPDemo'
        token: ${{ secrets.GITHUB_TOKEN }}
