name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: <https://make.powerapps.com/environments/Default-f926521e-0cde-404b-84af-812d6aa0c101>
        user-name: <davidhamilton@anctraining.onmicrosoft.com>
        password-secret: ${{ 'RubyRosie2!' }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: <https://make.powerapps.com/environments/Default-f926521e-0cde-404b-84af-812d6aa0c101>
        user-name: <davidhamilton@anctraining.onmicrosoft.com>
        password-secret: ${{ 'RubyRosie2!' }}
        solution-name: CDPDemo
        solution-output-file: out/exported/CDPDemo.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/CDPDemo.zip
        solution-folder: out/solutions/CDPDemo
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/CDPDemo
        solution-target-folder: solutions/CDPDemo
        repo-token: ${{ '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' }}
        allow-empty-commit: true
